export const StringLink = {
    dashboard:"/",
    tambahMitra:"/mitra",
    invoiceMitra:"/mitra/invoice",
    address:"/address",
    genealogy:"/genealogy",
    product:"/product",
    checkout:"/product/checkout",
    withdraw:"/withdraw",
    reportWithdraw:"/withdraw/report",
    reportTransaction:"/report/transaction",
    reportPurchase:"/report/purchase",
    transactionRecycle:"/recycle",
    invoiceRecycle:"/recycle/invoice",
    news:"/news",
    detailNews:"/news/:id_berita",
};